Einführung in SciPy und SymPy
=============================

1. IPython Grundlagen
---------------------

IPython ist eine interaktive Shell für Python. Startet man IPython mit

`> ipython notebook`

wird ein lokaler Webserver gestartet, so daß man mit
einem Browser neue Notebooks erstellen und editieren kann.

Ein Notebook besteht aus mehreren "Zellen" (Cells) die Python-Code oder
Markdown-formatierten Text enthalten können.


In [62]:
import numpy as np
print(np.__version__)
np

1.9.2


<module 'numpy' from '/home/speter/anaconda/lib/python2.7/site-packages/numpy/__init__.pyc'>

Code-Zellen enthalten eine auch mehrzeilige Eingabe.

Ausgeführt wird der Code in der Zelle mit `CTRL + RETURN`.

Eventuelle Ausgaben auf `sys.stdout` oder `sys.stderr` erscheinen direkt nach der Eingabebereich,
und der letzte Ausdruck wird im gesonderten Ausgabebereich angezeigt

In [2]:
np?

2. numpy Arrays
---------------

Das Grundlegenste Objekt in numpy ist das `array`.
Es ist ein mehrdimensionaler Container für Elemente des gleichen Typs.

In [18]:
np.array?

In [29]:
a = np.array([1,2,3,4], dtype=np.float32)
a

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [5]:
a.shape, a.dtype

((4,), dtype('float32'))

In [6]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [19]:
b = a.reshape( (2,2) )
b

array([[ 1.,  2.],
       [ 3.,  4.]], dtype=float32)

In [36]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

Man hieran erkennen, dass `a` eigene Daten besitzt (`OWNDATA: True`) und `b` nicht.
Das spart natürlich Speicher, kann aber auch leicht zu schwer lokalisierbaren Fehlern führen,
denn bei Änderungen an einem Objekt ändert sich auch das andere.


In [55]:
c = np.array( np.reshape(a, (2,2)) )
c.flags.owndata

True

Lineare Bereiche kann man mit `linspace` erstellen.
Man beachte, dass der Parameter `num` einen etwas willkürlichen Standardwert von 50 hat,
und man daher besser immer die gewünsche Anzahl eingeben sollte.

In [63]:
lin = np.linspace(1.0, 42.0, 42)
lin

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.])

### Arithmetik

In [61]:
lin + 1

array([  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
        24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,
        35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.])

Was ist da passiert? Die `1` wurde zu jedem Array-Element hinzuaddiert!

Das Verhalten nennt sich `broadcasting`: Was nicht passt, wird passend gemacht, 

In [65]:
lin*lin

array([  1.00000000e+00,   4.00000000e+00,   9.00000000e+00,
         1.60000000e+01,   2.50000000e+01,   3.60000000e+01,
         4.90000000e+01,   6.40000000e+01,   8.10000000e+01,
         1.00000000e+02,   1.21000000e+02,   1.44000000e+02,
         1.69000000e+02,   1.96000000e+02,   2.25000000e+02,
         2.56000000e+02,   2.89000000e+02,   3.24000000e+02,
         3.61000000e+02,   4.00000000e+02,   4.41000000e+02,
         4.84000000e+02,   5.29000000e+02,   5.76000000e+02,
         6.25000000e+02,   6.76000000e+02,   7.29000000e+02,
         7.84000000e+02,   8.41000000e+02,   9.00000000e+02,
         9.61000000e+02,   1.02400000e+03,   1.08900000e+03,
         1.15600000e+03,   1.22500000e+03,   1.29600000e+03,
         1.36900000e+03,   1.44400000e+03,   1.52100000e+03,
         1.60000000e+03,   1.68100000e+03,   1.76400000e+03])

Die Multiplikation ist bei `arrays` immer komponentenweise.